// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhNZ7HKZzI0mzIM3Ong84wzlyfKhamUPo',
    appId: '1:563596184131:web:66c56826959e8f5551e2f6',
    messagingSenderId: '563596184131',
    projectId: 'zomato-2-clone',
    authDomain: 'zomato-2-clone.firebaseapp.com',
    storageBucket: 'zomato-2-clone.appspot.com',
    measurementId: 'G-5J44YDJBPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRHDsOwdhcSbg0wS6_ShcGnYG7rLfjHd0',
    appId: '1:563596184131:android:323017609a11d69e51e2f6',
    messagingSenderId: '563596184131',
    projectId: 'zomato-2-clone',
    storageBucket: 'zomato-2-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvk1dCDZsVAoGUJWrZHvz-dBJiSc8Apo',
    appId: '1:563596184131:ios:330adff3e8d51cce51e2f6',
    messagingSenderId: '563596184131',
    projectId: 'zomato-2-clone',
    storageBucket: 'zomato-2-clone.appspot.com',
    iosBundleId: 'com.example.zomatoUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtvk1dCDZsVAoGUJWrZHvz-dBJiSc8Apo',
    appId: '1:563596184131:ios:9c52bf7d309a1e5451e2f6',
    messagingSenderId: '563596184131',
    projectId: 'zomato-2-clone',
    storageBucket: 'zomato-2-clone.appspot.com',
    iosBundleId: 'com.example.zomatoUsers.RunnerTests',
  );
}
